name: Get External Collections
run-name: 🚀 GEO | On  ${{ github.event.repository.updated_at}} - ${{github.ref_name}} by @${{ github.actor }}

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual trigger

jobs:
  download-repos:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Existing Repositories
        run: |
          for d in ./external/*/ ; do
              (cd "$d" && mv .gitoff .git && git fetch --all && git reset --hard HEAD && git pull --rebase && mv .git .gitoff)
          done

      - name: Clone New Repositories
        run: |
          while IFS= read -r repo; do
            repo_name=$(basename -s .git "$repo")
            repo_author=$(basename $(dirname "$repo"))
            repo_path="./external/${repo_author}-${repo_name}"
            if [ ! -d "$repo_path" ]; then
              echo "Cloning repository $repo"
              git clone "$repo" "$repo_path"
            fi
          done < ./external/collections.txt
